#! /usr/bin/env ruby

=begin
Generate a method function and its registration call in a C Ruby extension.
(c) Nicholas Booker, 2011
Licensed under GNU Lesser General Public License (LGPL) v3

Usage: methgen.rb clsobj prefix method [arg ...]
=end

if ARGV.count < 3 then
  $stderr.puts "Usage: #{$0} clsobj prefix method [arg ...]"
  exit 1
end

$clsobj = ARGV[0]
$prefix = ARGV[1]
$method = ARGV[2]
$argnames = ARGV.drop(3)

$funcname = "#{$prefix}_#{$method}"

$cargs = $argnames.map{|arg| ", VALUE #{arg}"}.join('')

puts <<END
//    rb_define_method(#{$clsobj}, "#{$method}", #{$funcname}, #{$argnames.count});
static VALUE #{$funcname}(VALUE self#{$cargs})
{
    // code here
}

END
